### ISSUE TITLE
Make it compatible with the Akeneo7.

### ISSUE THREAD

**Issue by vikasnick** [navneetbhardwaj/akeneo-quickexport-configurator#3]
### Preconditions (\*)

1. Akeneo version: CE 7.0.8 Sahara Hare
1. Module Version: 1.1.3
1. Mode: Production

### Steps to reproduce (\*)
* Getting issue on the terminal while adding the module in akeneo7.

### actual result (\*)
![image](https://user-images.githubusercontent.com/38047448/218701376-34d9f17d-4ef8-4224-b714-642b88548583.png)

**Comment by navneetbhardwaj** [comment]
added in the version #4 v1.1.4
